name: Publish package to Maven Central

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of the release
        required: true
        default: '1.0.0'
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven
        run: | 
          sudo apt-get install -y maven

      - name: Set up gpg
        run: |
          sudo apt-get install -y gnupg
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > private.key
          gpg --batch --import --verbose private.key

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>" > ~/.m2/settings.xml
          echo "  <servers>" >> ~/.m2/settings.xml
          echo "    <server>" >> ~/.m2/settings.xml
          echo "      <id>central</id>" >> ~/.m2/settings.xml
          echo "      <username>${{ secrets.CENTRAL_USERNAME }}</username>" >> ~/.m2/settings.xml
          echo "      <password>${{ secrets.CENTRAL_PASSWORD }}</password>" >> ~/.m2/settings.xml
          echo "    </server>" >> ~/.m2/settings.xml
          echo "    <server>" >> ~/.m2/settings.xml
          echo "      <id>gpg</id>" >> ~/.m2/settings.xml
          echo "      <username>${{ secrets.GPG_USERNAME }}</username>" >> ~/.m2/settings.xml
          echo "      <password>${{ secrets.GPG_PASSWORD }}</password>" >> ~/.m2/settings.xml
          echo "    </server>" >> ~/.m2/settings.xml
          echo "  </servers>" >> ~/.m2/settings.xml
          echo "</settings>" >> ~/.m2/settings.xml

      - name: Set version in pom.xml
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          elif [ "${{ github.event_name }}" == "release" ]; then
            VERSION="${{ github.event.release.tag_name }}"
          fi
          echo "Setting version to $VERSION"
          
          sed -i "s/<version>.*<\/version>/<version>$VERSION<\/version>/" pom.xml

      - name: Publish package to Maven Central
        run: mvn clean deploy -P release -DskipTests -Dgpg.passphrase=${{ secrets.GPG_PASSWORD }}
